services:
  - type: web
    name: gecko-web
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    healthCheckPath: /api/environment
    envVars:
      - key: PORT
        value: 8000
      - key: DATA_DIR
        value: /data
    disk:
      name: gecko-data
      mountPath: /data
      sizeGB: 10
